### PR TITLE
Fix/unstutter fixes #2

### LINKED ISSUE #2: Reduce stutter
Currently all tokenizer implementations have a class name ending in `Tokenizer`. This is pretty unnecessary if everything is instead under a `Tokenizer` module.

### PR DESCRIPTION
**Pull request by rmarronnier**
I'll prepare PRs to impact these changes in other repos.

### CODE REVIEW

**Comment by watzon** [comment]
Is this good to merge?

**Comment by rmarronnier** [comment]
Yes, with the caveats that :
- cadmium_util needs to be modified (::Regex) for the specs to pass
I'll do the cadmium_util change PR first, then the impacted shards prs today.

**Comment by watzon** [comment]
I'll just wait for the specs to be passing then :+1:

**Comment by rmarronnier** [comment]
`Cadmium_util` PR ready ;-)

**Pull request merged**
